# Generated by Django 5.0.7 on 2024-07-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develTools', '0002_rename_explan_develtool_content_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='interest',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tool',
        ),
        migrations.AddField(
            model_name='post',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='develTools.develtool', verbose_name='예상 개발툴'),
        ),
    ]
